"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowserClient} from "@/lib/supabase/browser";
type A={id:string;name:string;kind:string;status:string;url?:string};
export default function AgentsPage(){
 const [agents,setAgents]=useState<A[]>([]),[selected,setSelected]=useState("orchestrator"),[input,setInput]=useState(""),[messages,setMessages]=useState<string[]>([]),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/agents").then(r=>r.json()).then(x=>setAgents(x.agents??[])).catch(()=>{})},[]);
 const agent=agents.find(a=>a.id===selected);
 async function send(){const v=input.trim();if(!v||busy)return;setMessages(m=>[...m,"You: "+v]);setInput("");setBusy(true);try{const session=(await getSupabaseBrowserClient().auth.getSession()).data.session;const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+(session?.access_token??"")},body:JSON.stringify({agent:selected,messages:[{role:"user",content:v}]})});const p=await r.json();setMessages(m=>[...m,(agent?.name??selected)+": "+(p.message??p.error??"No response")])}finally{setBusy(false)}}
 return <main style={{minHeight:"100svh",background:"#070707",color:"#fff",fontFamily:"system-ui",padding:18,paddingBottom:90}}>
 <header style={{display:"flex",justifyContent:"space-between"}}><div><small style={{opacity:.5}}>ELEVAT AI</small><h1 style={{margin:"4px 0"}}>Agent Command</h1></div><small>GLOBAL LOOP ON</small></header>
 <div style={{display:"grid",gap:9,marginTop:16}}>{agents.map(a=><button key={a.id} onClick={()=>setSelected(a.id)} style={{textAlign:"left",padding:14,borderRadius:15,border:a.id===selected?"1px solid #8cffb0":"1px solid #292929",background:"#111",color:"#fff"}}><b>{a.name}</b><span style={{float:"right",fontSize:11,opacity:.65}}>{a.status}</span><div style={{fontSize:12,opacity:.5,marginTop:5}}>{a.kind}</div></button>)}</div>
 <section style={{marginTop:14,padding:15,border:"1px solid #292929",borderRadius:17}}><small style={{opacity:.5}}>ACTIVE</small><h2>{agent?.name??selected}</h2><div style={{minHeight:190,padding:12,background:"#050505",borderRadius:12}}>{messages.map((m,i)=><div key={i} style={{marginBottom:10}}>{m}</div>)}</div><div style={{display:"flex",gap:8,marginTop:10}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Give this agent a task..." style={{flex:1,padding:12,borderRadius:11,border:"1px solid #333",background:"#151515",color:"#fff"}}/><button onClick={send} disabled={busy} style={{padding:"0 15px",borderRadius:11}}>{busy?"...":"Send"}</button></div>{agent?.url&&<a href={agent.url} target="_blank" rel="noreferrer" style={{display:"inline-block",marginTop:12,color:"#8cffb0"}}>Open Robin</a>}</section>
 <nav style={{position:"fixed",bottom:0,left:0,right:0,padding:12,background:"#090909",borderTop:"1px solid #222",display:"flex",justifyContent:"space-around",fontSize:12}}><span>Agents</span><span>Tasks</span><span>Activity</span><span>Settings</span></nav>
 </main>
}